### ISSUE TITLE
The one-click deploy.sh script is faulty, causing front-end startup errors

### ISSUE THREAD

**Issue by yikaixiong** [chobynleo/pancakeswap-frontend-hardhat-testnet#3]
deploy.sh  error: 

Error: ENOENT: no such file or directory, mkdir '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/deployments/31337'
    at Object.mkdirSync (node:fs:1336:3)
    at writeAddr (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/hardhat-token/scripts/artifact_log.js:19:8)
    at main (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/hardhat-token/scripts/deploy.js:29:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/deployments/31337'
}

Error: Cannot find module '../../deployments/31337/SyrupBar.json'
Require stack:
- /Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-swap-core/scripts/deploy.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-swap-core/scripts/deploy.js:2:22)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

.......

start.sh error : 

./node_modules/local-pancakeswap-libs/sdk/dist/sdk.esm.js
Module not found: Can't resolve '../../../../../deployments/31337/INIT_CODE_PAIR_HASH.json' in '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-frontend/node_modules/local-pancakeswap-libs/sdk/dist'

**Comment by chobynleo** [comment]
> deploy.sh error:
> 
> Error: ENOENT: no such file or directory, mkdir '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/deployments/31337' at Object.mkdirSync (node:fs:1336:3) at writeAddr (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/hardhat-token/scripts/artifact_log.js:19:8) at main (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/hardhat-token/scripts/deploy.js:29:11) at processTicksAndRejections (node:internal/process/task_queues:96:5) { errno: -2, syscall: 'mkdir', code: 'ENOENT', path: '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/deployments/31337' }
> 
> Error: Cannot find module '../../deployments/31337/SyrupBar.json' Require stack:
> 
> * /Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-swap-core/scripts/deploy.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-swap-core/scripts/deploy.js:2:22)
>   at Module._compile (node:internal/modules/cjs/loader:1103:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
> 
> .......
> 
> start.sh error :
> 
> ./node_modules/local-pancakeswap-libs/sdk/dist/sdk.esm.js Module not found: Can't resolve '../../../../../deployments/31337/INIT_CODE_PAIR_HASH.json' in '/Users/cecilia-xiaoyu/code/pancakeswap-frontend-hardhat-testnet/pancake-frontend/node_modules/local-pancakeswap-libs/sdk/dist'

Hi, You should create a new `deployments` folder( save chain msg) for your local environment
