### ISSUE TITLE
deploy.sh errors

### ISSUE THREAD

**Issue by tcscat** [chobynleo/pancakeswap-frontend-hardhat-testnet#4]
Compilation finished successfully
Error: Cannot find module '../../deployments/31337/SyrupBar.json'
Require stack:
- /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-core/scripts/deploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-core/scripts/deploy.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Compiling 25 files with 0.6.6
Compilation finished successfully
Error: Cannot find module '../../../deployments/31337/INIT_CODE_PAIR_HASH.json'
Require stack:
- /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/writeFile/writeFile.js
- /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/deploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/writeFile/writeFile.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by chobynleo** [comment]
> Compilation finished successfully Error: Cannot find module '../../deployments/31337/SyrupBar.json' Require stack:
> 
> * /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-core/scripts/deploy.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>   at Module.require (internal/modules/cjs/loader.js:887:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-core/scripts/deploy.js:2:22)
>   at Module._compile (internal/modules/cjs/loader.js:999:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>   at Module.load (internal/modules/cjs/loader.js:863:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>   Compiling 25 files with 0.6.6
>   Compilation finished successfully
>   Error: Cannot find module '../../../deployments/31337/INIT_CODE_PAIR_HASH.json'
>   Require stack:
> * /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/writeFile/writeFile.js
> * /home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/deploy.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>   at Module.require (internal/modules/cjs/loader.js:887:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/tcscat/Downloads/pancakeswap-frontend-hardhat-testnet-master/pancake-swap-periphery/scripts/writeFile/writeFile.js:5:34)
>   at Module._compile (internal/modules/cjs/loader.js:999:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>   at Module.load (internal/modules/cjs/loader.js:863:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>   at Module.require (internal/modules/cjs/loader.js:887:19)

Thanks, I've fixed it.
Please `git pull` and try again.
